name: Build
on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Cache for Dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json') }}
    
    - name: Install dependencies
      run: npm i
    
    - name: Build
      run: npm run compile
    
    - name: Commit compiled
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Action
        author_email: engineering@quizizz.com
        message: 'Compile TS'
        add: '. ./dist --force'
