name: Unit Tests
on:
  push:
    branches:
      - main
      - v*
  pull_request:
    branches:
      - main

  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Cache for Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm i
      
      - name: Run Tests
        run: npm run test:ci
